version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Source"
    schedule:
      interval: "daily"
    groups:
      cake-dependencies:
        patterns:
          - "Cake.Core"
          - "Cake.Testing"
        update-types:
          - "major"
    ignore:
      - dependency-name: "Cake.Core"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
